### ISSUE TITLE
Actualización Página Servicio Social

### ISSUE THREAD

**Issue by Ale-Coeto** [WIT-MTY/webpage#14]
- Actualizar imágenes
- Verificar que funcione bien el carrousel
- Agregar objetivo
- Agregar cartas de info

**Comment by Caroramirezz** [comment]
Where estan las imagenes a actualizar?🧐

**Comment by Ale-Coeto** [comment]
Hay que pedírselas a marketing, ahorita le escribo a la subdire

**Comment by Ale-Coeto** [comment]
Aquí hay varias fotitos: https://drive.google.com/drive/folders/13u6kmkMMON9oiu5hL5f0KOOe9YkTa82c?usp=sharing
